[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "bruh"
authors = [{name = "parth", email = "sarkar.parth17@gmail.com"}]
dynamic = ["version", "description"]
